import type { Metadata } from "next";
import { Anton_SC, Heebo } from "next/font/google";
import "./globals.css";
import GlobalHeader from "@/components/global/global-header";
import GlobalFooter from "@/components/global/global-footer";

const antonSC = Anton_SC({
  variable: "--font-anton-sc",
  subsets: ["latin"],
  weight: "400",
});

const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${antonSC.variable} ${heebo.variable} antialiased`}
      >
        <GlobalHeader />
        {children}
        <GlobalFooter />
      </body>
    </html>
  );
}
